#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

H_DNS_SERVER_0="fc4d:c8e5:9efe:9ac2:8e72:fcf7:6ce8:39dc"
H_DNS_SERVER_1="fc6e:691e:dfaa:b992:a10a:7b49:5a1a:5e09"
H_DNS_SERVER_2="fc16:b44c:2bf9:467:8098:51c6:5849:7b4f"

# Create radvd.conf before installing radvd, installation fails without it
if ! [ -f /etc/radvd.conf ]; then 
    sudo cp "$BASE_DIR/radvd.conf" /etc/radvd.conf
fi

sudo apt-get install -y confget hostapd radvd iptables bridge-utils dnsmasq

#check if orange pi needs this line
systemctl enable systemd-networkd || true 
systemctl enable systemd-networkd.service || true

APSSID=$(sudo grep -m 1 '"ipv6"' /etc/cjdroute.conf | awk '{ print $2 }' | sed 's/[",]//g' | sed "s/.*:/$MESH_NAME-/g")

# Select wpa-eap or wpa-psk
read -p "Use WPA-EAP (Y) or WPA2-PSK (n) for WiFi Access Point $APSSID? " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Nn]$ ]]; then
    USE_EAP=false
    while [ "${#APPASS}" -lt 8 ] || [ "${#APPASS}" -gt 63 ]; do
        read -p "Set WPA2-PSK password (8-63 characters): " APPASS;
    done
else
    USE_EAP=true
    while [ "${#APPASS}" -lt 8 ] || [ "${#APPASS}" -gt 63 ]; do
        read -p "Set WPA-EAP password (8-63 characters) for user \"guest\": " APPASS;
    done
fi

sudo cp $BASE_DIR/75-lan-bridge.netdev /etc/systemd/network/75-lan-bridge.netdev
sudo cp $BASE_DIR/75-lan-bridge.network /etc/systemd/network/75-lan-bridge.network

sudo cp $BASE_DIR/95-wlan-hostap.link /etc/systemd/network/95-wlan-hostap.link
sudo sed -i "s/##SSID##/$APSSID/g" "/etc/systemd/network/95-wlan-hostap.link"

sudo cp $BASE_DIR/95-wlan-hostap.network /etc/systemd/network/95-wlan-hostap.network
if [ "$USE_EAP" = true ]; then
    sudo cp $BASE_DIR/wpa-eap/hostapd.template.conf /etc/hostapd/hostapd.template.conf
    sudo cp "$BASE_DIR/wpa-eap/hostapd.eap_user" /etc/hostapd/hostapd.eap_user
    sudo echo "\"guest\" MSCHAPV2 \"$APPASS\" [2]" | sudo tee --append /etc/hostapd/hostapd.eap_user > /dev/null
    sudo sed -i "s/wpa_passphrase=##PSK##//g" "/etc/systemd/network/95-wlan-hostap.link"
    cp -r "$BASE_DIR/wpa-eap/certs" "$BASE_DIR/tmp"
    /bin/bash "$BASE_DIR/tmp/bootstrap"
    sudo cp "$BASE_DIR/tmp/ca.pem" /etc/hostapd/ca.pem
    sudo cp "$BASE_DIR/tmp/server.pem" /etc/hostapd/server.pem
    rm -rf "$BASE_DIR/tmp"

else
    sudo cp $BASE_DIR/wpa-psk/hostapd.template.conf /etc/hostapd/hostapd.template.conf
    sudo sed -i "s/##PSK##/$APPASS/g" "/etc/systemd/network/95-wlan-hostap.link"
fi


# Enable packet forwarding
sudo cp /etc/sysctl.conf /etc/sysctl.conf.bak
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sudo sed -i 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/' /etc/sysctl.conf

sudo cp $BASE_DIR/50-hostapd.rules /etc/udev/rules.d/50-hostapd.rules 

sudo systemctl daemon-reload
sudo systemctl enable radvd.service
sudo systemctl start radvd.service

sudo cp $BASE_DIR/hostapd.template /usr/local/sbin/hostapd.template
sudo chmod 744 /usr/local/sbin/hostapd.template

sudo cp $BASE_DIR/hostapd\@.service /etc/systemd/system/hostapd\@.service  

sudo cp "$BASE_DIR/hostapd.nat" /usr/local/sbin/hostapd.nat
sudo chmod 744 /usr/local/sbin/hostapd.nat

sudo cp $BASE_DIR/radvd.conf "/etc/radvd.conf"


echo "source-directory /etc/network/interfaces.d" | sudo tee --append /etc/network/interfaces > /dev/null
echo "" | sudo tee --append /etc/network/interfaces > /dev/null
echo "auto lo"  | sudo tee --append /etc/network/interfaces > /dev/null
echo "iface lo inet loopback" | sudo tee --append /etc/network/interfaces > /dev/null
echo "" | sudo tee --append /etc/network/interfaces > /dev/null
echo "allow-hotplug wlan0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "iface wlan0 inet static" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    address 10.0.0.1" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    netmask 255.255.255.0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    network 10.0.0.0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    broadcast 10.0.0.255" | sudo tee --append /etc/network/interfaces > /dev/null
echo "iface wlan0 inet6 static" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    address fdfc::2" | sudo tee --append /etc/network/interfaces > /dev/null
echo "    netmask 64" | sudo tee --append /etc/network/interfaces > /dev/null
echo "" | sudo tee --append /etc/network/interfaces > /dev/null
echo "allow-hotplug eth0" | sudo tee --append /etc/network/interfaces > /dev/null
echo "iface eth0 inet dhcp" | sudo tee --append /etc/network/interfaces > /dev/null

# Configure DHCP with dnsmasq
if [ -f /etc/dnsmasq.conf ]; then
    sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
fi
sudo cp "$BASE_DIR/dnsmasq.conf" /etc/dnsmasq.conf
