#!/usr/bin/env bash

set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

wget https://github.com/darkdrgn2k/ToMeshPackages/blob/master/aether/aether-be-pre01-armv6l.bin /tmp
sudo mv /tmp/aether-be-pre01-armv6l.bin /usr/local/bin/aether-be

currentUser=$USER

cp "$BASE_DIR/aether-be.service" /tmp
sudo sed -i "s|__USER__|${currentUser}|g" /tmp/aether-be.service
sudo mv "/tmp/aether-be.service" /etc/systemd/system/aether-be.service

sudo systemctl daemon-reload
sudo systemctl enable aether-be.service
sudo systemctl start aether-be.service
