#!/usr/bin/env bash

set -e

AETHER_VERSION="pre01"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

wget https://github.com/darkdrgn2k/ToMeshPackages/raw/master/aether/aether-be-${AETHER_VERSION}-armv6l.bin -O /tmp/aether-be
chmod +x /tmp/aether-be
sudo mv /tmp/aether-be /usr/local/bin/aether-be

currentUser=$USER

cp "$BASE_DIR/aether-be.service" /tmp
sudo sed -i "s|__USER__|${currentUser}|g" /tmp/aether-be.service
sudo mv "/tmp/aether-be.service" /etc/systemd/system/aether-be.service

sudo systemctl daemon-reload
sudo systemctl enable aether-be.service
sudo systemctl start aether-be.service
